#ifndef _KC705_DEVICE_H
#define _KC705_DEVICE_H

//driver struct
#define PCIE_DEVICE_IOCTL_BASE	'W'
#define PCIE_DEVICE_IOCTL_START_DMA_THREAD _IO(PCIE_DEVICE_IOCTL_BASE, 0)
#define PCIE_DEVICE_IOCTL_STOP_DMA_THREAD _IO(PCIE_DEVICE_IOCTL_BASE, 1)

//driver struct

#endif//#ifndef _KC705_DEVICE_H
