// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.3
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xotsu2.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XOtsu2_CfgInitialize(XOtsu2 *InstancePtr, XOtsu2_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Control_bus_BaseAddress = ConfigPtr->Control_bus_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XOtsu2_Start(XOtsu2 *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XOtsu2_ReadReg(InstancePtr->Control_bus_BaseAddress, XOTSU2_CONTROL_BUS_ADDR_AP_CTRL) & 0x80;
    XOtsu2_WriteReg(InstancePtr->Control_bus_BaseAddress, XOTSU2_CONTROL_BUS_ADDR_AP_CTRL, Data | 0x01);
}

u32 XOtsu2_IsDone(XOtsu2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XOtsu2_ReadReg(InstancePtr->Control_bus_BaseAddress, XOTSU2_CONTROL_BUS_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XOtsu2_IsIdle(XOtsu2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XOtsu2_ReadReg(InstancePtr->Control_bus_BaseAddress, XOTSU2_CONTROL_BUS_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XOtsu2_IsReady(XOtsu2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XOtsu2_ReadReg(InstancePtr->Control_bus_BaseAddress, XOTSU2_CONTROL_BUS_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XOtsu2_EnableAutoRestart(XOtsu2 *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XOtsu2_WriteReg(InstancePtr->Control_bus_BaseAddress, XOTSU2_CONTROL_BUS_ADDR_AP_CTRL, 0x80);
}

void XOtsu2_DisableAutoRestart(XOtsu2 *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XOtsu2_WriteReg(InstancePtr->Control_bus_BaseAddress, XOTSU2_CONTROL_BUS_ADDR_AP_CTRL, 0);
}

u32 XOtsu2_GetReturn(XOtsu2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XOtsu2_ReadReg(InstancePtr->Control_bus_BaseAddress, XOTSU2_CONTROL_BUS_ADDR_AP_RETURN);
    return Data;
}
void XOtsu2_SetRows(XOtsu2 *InstancePtr, u32 Data) {
	printf("xiaofei: %s:%d InstancePtr->Control_bus_BaseAddress:%x\n", __func__, __LINE__, InstancePtr->Control_bus_BaseAddress);
	printf("xiaofei: %s:%d XOTSU2_CONTROL_BUS_ADDR_ROWS_DATA:%x\n", __func__, __LINE__, XOTSU2_CONTROL_BUS_ADDR_ROWS_DATA);
	printf("xiaofei: %s:%d Data:%x\n", __func__, __LINE__, Data);
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XOtsu2_WriteReg(InstancePtr->Control_bus_BaseAddress, XOTSU2_CONTROL_BUS_ADDR_ROWS_DATA, Data);
}

u32 XOtsu2_GetRows(XOtsu2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XOtsu2_ReadReg(InstancePtr->Control_bus_BaseAddress, XOTSU2_CONTROL_BUS_ADDR_ROWS_DATA);
    return Data;
}

void XOtsu2_SetCols(XOtsu2 *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XOtsu2_WriteReg(InstancePtr->Control_bus_BaseAddress, XOTSU2_CONTROL_BUS_ADDR_COLS_DATA, Data);
}

u32 XOtsu2_GetCols(XOtsu2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XOtsu2_ReadReg(InstancePtr->Control_bus_BaseAddress, XOTSU2_CONTROL_BUS_ADDR_COLS_DATA);
    return Data;
}

void XOtsu2_InterruptGlobalEnable(XOtsu2 *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XOtsu2_WriteReg(InstancePtr->Control_bus_BaseAddress, XOTSU2_CONTROL_BUS_ADDR_GIE, 1);
}

void XOtsu2_InterruptGlobalDisable(XOtsu2 *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XOtsu2_WriteReg(InstancePtr->Control_bus_BaseAddress, XOTSU2_CONTROL_BUS_ADDR_GIE, 0);
}

void XOtsu2_InterruptEnable(XOtsu2 *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XOtsu2_ReadReg(InstancePtr->Control_bus_BaseAddress, XOTSU2_CONTROL_BUS_ADDR_IER);
    XOtsu2_WriteReg(InstancePtr->Control_bus_BaseAddress, XOTSU2_CONTROL_BUS_ADDR_IER, Register | Mask);
}

void XOtsu2_InterruptDisable(XOtsu2 *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XOtsu2_ReadReg(InstancePtr->Control_bus_BaseAddress, XOTSU2_CONTROL_BUS_ADDR_IER);
    XOtsu2_WriteReg(InstancePtr->Control_bus_BaseAddress, XOTSU2_CONTROL_BUS_ADDR_IER, Register & (~Mask));
}

void XOtsu2_InterruptClear(XOtsu2 *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XOtsu2_WriteReg(InstancePtr->Control_bus_BaseAddress, XOTSU2_CONTROL_BUS_ADDR_ISR, Mask);
}

u32 XOtsu2_InterruptGetEnabled(XOtsu2 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XOtsu2_ReadReg(InstancePtr->Control_bus_BaseAddress, XOTSU2_CONTROL_BUS_ADDR_IER);
}

u32 XOtsu2_InterruptGetStatus(XOtsu2 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XOtsu2_ReadReg(InstancePtr->Control_bus_BaseAddress, XOTSU2_CONTROL_BUS_ADDR_ISR);
}

