#
#
#================================================================
#   Copyright (C) 2017年11月14日 肖飞 All rights reserved.
#   
#   文件名称：Makefile
#   创 建 者：肖飞
#   创建日期：2017年11月14日 星期二 14时58分03秒
#   修改日期：2017年11月14日 星期二 15时07分14秒
#   描    述：
#
#================================================================
ifneq ($(target),)
include $(target).mk
default:
	echo message is $(message)
endif

error:
	echo error occured!!!

t1:
	make -f Makefile target=$@

t2:
	make -f Makefile target=$@

t3:
	make -f Makefile target=$@
