#ifndef _MAIN_HEADER_
#define _MAIN_HEADER_
enum{
	CREATE_CHAIN_HEADER=1,
	CALC_CHAIN_TAIL,
	SORT_RAINBOW_TABLE,
	MERGE_RAINBOW_TABLE,
	CREATE_TABLE_INDEX,
	CRACK_DES,	
	MAX_OP_MODE
};
#define ITEM_COUNT_INTABLE 5629499534L// // 2^48/50000/5
#define TABLE_COUNT		5
#define CALC_QUEUE_LEN 50000
#define CHAIN_HEADER_LENGTH 5
#define CHAIN_TAIL_LENGTH 6


#endif
