include $(default_rules)
CC := gcc
#sysroot := /home/xiaofei/workspace/src/6818/x6818_linux_160719/buildroot/output/host

#CFLAGS_INCLUDE += -I$(sysroot)/usr/include
#CFLAGS += $(CFLAGS_INCLUDE)
#LIBS_DIR += -L$(sysroot)/usr/lib
#LIBS := 
#LDFLAGS += $(LIBS_DIR) $(LIBS)
#TOOLCHAIN_PREFIX := /home/xiaofei/workspace/src/6818/x6818_linux_160719/buildroot/output/host/opt/ext-toolchain/bin/arm-cortex_a9-linux-gnueabi-


c_files := nl-uevent.c
include $(BUILD_BINS)

include $(ADD_TARGET)
