include $(default_rules)

c_files := insert_file.cpp
c_files += insert_code.cpp
c_files += rom_header.cpp
c_files += find_header.cpp 
c_files += search.cpp 
c_files += mips_dasm.cpp

include $(BUILD_BINS)

include $(ADD_TARGET)
