# *-* coding: utf-8 *-*

import sys

origin_list = [
	'FMC_HPC_HA23_N',
	'FMC_HPC_HA23_P',
	'FMC_HPC_HA21_N',
	'FMC_HPC_HA21_P',
	'FMC_HPC_HA17_CC_N',
	'FMC_HPC_HA17_CC_P',
	'FMC_HPC_HA10_N',
	'FMC_HPC_HA10_P',
	'FMC_HPC_HA06_N',
	'FMC_HPC_HA06_P',
	'FMC_HPC_HA02_N',
	'FMC_HPC_HA02_P',
	'FMC_HPC_LA30_N',
	'FMC_HPC_LA30_P',
	'FMC_HPC_HA22_N',
	'FMC_HPC_HA22_P',
	'FMC_HPC_HA18_N',
	'FMC_HPC_HA18_P',
	'FMC_HPC_HA14_N',
	'FMC_HPC_HA14_P',
	'FMC_HPC_HA11_N',
	'FMC_HPC_HA11_P',
	'FMC_HPC_HA07_N',
	'FMC_HPC_HA07_P',
	'FMC_HPC_HA03_N',
	'FMC_HPC_HA03_P',
	'FMC_HPC_LA33_N',
	'FMC_HPC_LA31_N',
	'FMC_HPC_LA28_N',
	'FMC_HPC_LA28_P',
	'FMC_HPC_LA24_N',
	'FMC_HPC_LA24_P',
	'FMC_HPC_LA21_N',
	'FMC_HPC_LA21_P',
	'FMC_HPC_LA19_P',
	'FMC_HPC_LA15_P',
	'FMC_HPC_LA11_P',
	'FMC_HPC_LA07_P',
	'FMC_HPC_LA04_P',
	'FMC_HPC_LA02_P',
	'FMC_HPC_CLK0_M2C_P',
	'FMC_HPC_LA32_N',
	'FMC_HPC_LA22_N',
	'FMC_HPC_LA31_P',
	'FMC_HPC_LA29_N',
	'FMC_HPC_LA29_P',
	'FMC_HPC_LA25_N',
	'FMC_HPC_LA25_P',
	'FMC_HPC_LA19_N',
	'FMC_HPC_LA15_N',
	'FMC_HPC_LA11_N',
	'FMC_HPC_LA07_N',
	'FMC_HPC_LA04_N',
	'FMC_HPC_LA02_N',
	'FMC_HPC_CLK0_M2C_N',
	'FMC_HPC_PRSNT_M2C_B_LS',
	'FMC_HPC_LA22_P',
	'FMC_HPC_LA20_N',
	'FMC_HPC_LA16_N',
	'FMC_HPC_LA20_P',
	'FMC_HPC_LA12_N',
	'FMC_HPC_LA16_P',
	'FMC_HPC_LA12_P',
	'FMC_HPC_LA08_N',
	'FMC_HPC_LA08_P',
	'FMC_HPC_LA03_N',
	'FMC_HPC_LA03_P',
	'FMC_HPC_LA00_CC_N',
	'FMC_HPC_LA00_CC_P',
	'FMC_HPC_CLK1_M2C_N',
	'FMC_HPC_CLK1_M2C_P',
	'FMC_HPC_LA32_P',
	'FMC_HPC_LA33_P',
	'FMC_HPC_HA19_N',
	'FMC_HPC_HA19_P',
	'FMC_HPC_HA15_N',
	'FMC_HPC_HA15_P',
	'FMC_HPC_HA12_N',
	'FMC_HPC_HA12_P',
	'FMC_HPC_HA08_N',
	'FMC_HPC_HA08_P',
	'FMC_HPC_HA04_N',
	'FMC_HPC_HA04_P',
	'FMC_HPC_HA00_CC_N',
	'FMC_HPC_HA00_CC_P',
	'FMC_HPC_PG_M2C_LS',
	'FMC_HPC_HA20_N',
	'FMC_HPC_HA20_P',
	'FMC_HPC_HA16_N',
	'FMC_HPC_HA16_P',
	'FMC_HPC_HA13_N',
	'FMC_HPC_HA13_P',
	'FMC_HPC_HA09_N',
	'FMC_HPC_HA09_P',
	'FMC_HPC_HA05_N',
	'FMC_HPC_HA05_P',
	'FMC_HPC_HA01_CC_N',
	'FMC_HPC_HA01_CC_P',
	'FMC_HPC_LA26_N',
	'FMC_HPC_LA26_P',
	'FMC_HPC_LA23_N',
	'FMC_HPC_LA23_P',
	'FMC_HPC_LA17_CC_N',
	'FMC_HPC_LA17_CC_P',
	'FMC_HPC_LA13_N',
	'FMC_HPC_LA13_P',
	'FMC_HPC_LA09_N',
	'FMC_HPC_LA09_P',
	'FMC_HPC_LA06_P',
	'FMC_HPC_LA27_N',
	'FMC_HPC_LA27_P',
	'FMC_HPC_LA18_CC_N',
	'FMC_HPC_LA18_CC_P',
	'FMC_HPC_LA14_N',
	'FMC_HPC_LA14_P',
	'FMC_HPC_LA10_N',
	'FMC_HPC_LA10_P',
	'FMC_HPC_LA05_N',
	'FMC_HPC_LA05_P',
	'FMC_HPC_LA01_CC_N',
	'FMC_HPC_LA01_CC_P',
	'FMC_HPC_LA06_N',
	'FMC_C2M_PG_LS',
]

def process_data(filename):
	t = ''
	with open(filename) as f:
		t = f.read()
	l = t.strip().splitlines()
	s = []
	d = {}
	for i in l:
		io, status = i.split()
		if not io in s:
			s.append(io)
		d[io] = status
	for i in range(len(s)):
		if s[i] != origin_list[i]:
			print 'ERROR!!!!!!!!!!!!!!!!'
			return
		print '%-30s%-10s' %(s[i], d.get(s[i]))
if __name__ == '__main__':
	process_data(sys.argv[1])
